---
service:
  loadBalancerIP: ""
management:
  loadBalancerIP: ""

nats:
  podTemplate:
    patch:
      - op: add
        path: /spec/securityContext
        value:
          sysctls:
            - name: net.core.somaxconn
              value: "16384"

  natsBox:
    enabled: false

  reloader:
    enabled: false

  config:
    cluster:
      noAdvertise: true
      enabled: true
      replicas: 1
    jetstream:
      enabled: false

  container:
    merge:
      resources:
        requests:
          cpu: 2
          memory: 1Gi
          ephemeral-storage: 500Mi
        limits:
          cpu: 4
          memory: 1Gi
          ephemeral-storage: 500Mi

  promExporter:
    enabled: true
    env:
      GODEBUG: multipathtcp=0
    podMonitor:
      enabled: true
