apiVersion: v2
name: clickhouse
description: Minimal wrapper chart for a single-node ClickHouse on OpenShift
type: application
version: 0.1.0

dependencies:
  - name: clickhouse
    version: 0.3.6
    repository: "https://altinity.github.io/helm-charts"
