clickhouse:
  defaultUser:
    password: "secret"
    allowExternalAccess: false

  replicasCount: 1
  shardsCount: 1

  persistence:
    enabled: true
    size: 10Gi
    storageClass: "ceph-rbd"

  logs:
    enabled: true

  service:
    type: ClusterIP

  operator:
    enabled: false

  podSecurityContext: {}
  securityContext: {}
