apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pulsar.fullname" . }}
  labels:
    {{- include "pulsar.labels" . | nindent 4 }}
data:
  config.yaml: |
{{ .Values.config.contents | indent 4 }}
