apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: {{ include "pulsar.fullname" . }}
  labels:
    {{- include "pulsar.labels" . | nindent 4 }}
spec:
  ingressClassName: private
  routes:
    - services:
        - name: {{ include "pulsar.fullname" . }}
          port: {{ .Values.service.port }}
          weight: 100
      timeoutPolicy:
        response: 2m
        idle: 2m
        idleConnection: 2m
  virtualhost:
    fqdn: "pulsar.apps.private.okd4.teh-2.snappcloud.io"
