apiVersion: v1
kind: Service
metadata:
  name: {{ include "pulsar.fullname" . }}
  labels:
    {{- include "pulsar.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "pulsar.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
